version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      mongodb_net:
        aliases:
          - mongodb-rs

networks:
  mongodb_net:
    name: mongodb_net
    driver: bridge